#Define a multi-part driver
obj - $(CONFIG_GPTP) += gptp.o gptp - objs:= gptp_main.o gptp_messages.o
    gptp_pdelay_state.o gptp_state.o
    gptp_rtc.o gptp_arithmetic.o
    gptp_netlink.o gptp_fpga.o gptp_bmca_announce_state.o
